[build]
  # Use pnpm if your project uses pnpm (you can change to "npm run build" or "yarn build" if needed)
  command = "pnpm build"
  # This project builds a static export into `out` (because `next.config.mjs` uses `output: 'export'`)
  publish = "out"
